### ISSUE TITLE
谁来给个step by step的安装使用说明

### ISSUE THREAD

**Issue by ZanoZ** [l15y/wenda#11]
pip安装之后，开始迷茫了，不知道接下来做啥啊啊啊。。。。
难道需要去问问gpt咩。。。

**Comment by l15y** [comment]
模型下好，直接运行

**Comment by adili001** [comment]
建议直接下载使用README.md里给的那个懒人包。下载好，解压后直接双击run_GLM6B.bat就行了。

**Comment by adogshz** [comment]
这里人不多啊，闻达还是很有前景的开源项目，先标个小🌟

**Comment by WilsonWu315** [comment]
在Linux下跑不起来，还是要有人来搞个安装程序才行

**Comment by l15y** [comment]
> 在Linux下跑不起来，还是要有人来搞个安装程序才行

我目前提供的启动脚本适用于windows，liunx需要把其中set替换为export

**Comment by WilsonWu315** [comment]
嗯嗯，我已经改了环境变量了，现在我想gen data，但出这个错了，请问怎么解决？
root@autodl-container-cfb111adb0-820abbbb:~/workspace/wenda# python gen_data.py
glm模型地址 model/chatglm-6b-int4
embeddings模型地址 model/simcse-chinese-roberta-wwm-ext
vectorstore保存地址 xw
chunk_size 600
chunk_count 1
rwkv模型地址 ../RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth
rwkv模型参数 cuda fp16i8 *16+
日志记录 True
开始读取数据
Traceback (most recent call last):
  File "gen_data.py", line 28, in <module>
    docs = loader.load()
  File "/root/miniconda3/lib/python3.8/site-packages/langchain/document_loaders/directory.py", line 55, in load
    raise e
  File "/root/miniconda3/lib/python3.8/site-packages/langchain/document_loaders/directory.py", line 49, in load
    sub_docs = self.loader_cls(str(i)).load()
  File "/root/miniconda3/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py", line 35, in load
    elements = self._get_elements()
  File "/root/miniconda3/lib/python3.8/site-packages/langchain/document_loaders/unstructured.py", line 29, in _get_elements
    from unstructured.partition.auto import partition
ModuleNotFoundError: No module named 'unstructured.partition.auto'

**Comment by l15y** [comment]
@WilsonWu315 别用这个了，sentence-transformer效果迷一样的不好。新版本，我替换成基于关键词的搜索了
