### ISSUE TITLE
Ubuntu 运行 'bash run_GLM6B.sh' 后报错

### ISSUE THREAD

**Issue by Yamol** [l15y/wenda#117]
**Describe the bug**
`(pytorch) devops@ubuntu22:~/git/wenda$ bash run_GLM6B.sh
WebUI 端口号 None
LLM模型类型 glm6b
glm模型地址 /home/devops/database/chatglm_6b/full
glm模型参数 cuda fp16
日志记录 True
知识库类型 s
知识库显示来源 False
chunk_size 400
chunk_count 3
知识库文件夹名称为: /home/devops/proj/poctip_gpt.20230406/doc/txt
Traceback (most recent call last):
  File "/home/devops/git/wenda/wenda.py", line 218, in <module>
    bottle.run(server='paste', host="0.0.0.0", port=settings.port, quiet=True)
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/bottle.py", line 3157, in run
    server = server(host=host, port=port, **kargs)
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/bottle.py", line 2753, in __init__
    self.port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/jieba/analyse/tfidf.py:47: ResourceWarning: unclosed file <_io.BufferedReader name='/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/jieba/analyse/idf.txt'>
  content = open(new_idf_path, 'rb').read().decode('utf-8')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
 知识库加载完成
2023-04-13 06:56:09.721912: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-13 06:56:09.794272: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-13 06:56:10.706709: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/devops/git/wenda/wenda.py", line 198, in load_model
    LLM.load_model()
  File "/home/devops/git/wenda/plugins/llm_glm6b.py", line 30, in load_model
    from transformers import AutoModel, AutoTokenizer
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/transformers/utils/generic.py", line 33, in <module>
    import tensorflow as tf
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 31, in <module>
    from . import compat
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 332, in <module>
    from tensorboard.summary._tf import summary
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 19, in <module>
    from . import pywrap_tensorflow
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 22, in <module>
    from .io import gfile
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/__init__.py", line 17, in <module>
    from . import gfile  # noqa
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 40, in <module>
    import fsspec
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/fsspec/__init__.py", line 3, in <module>
    from . import _version, caching
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/site-packages/fsspec/caching.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/concurrent/futures/thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "/home/devops/app/anaconda3/envs/pytorch/lib/python3.9/threading.py", line 1414, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown`

**Comment by Yamol** [comment]
然后一直循环

**Comment by l15y** [comment]
下次贴问题，保留格式。
文本编码不对
