### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by daba0007** [l15y/wenda#132]
```
/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py:1227: DeprecationWarning: invalid escape sequence \?
  ["\?", "？"],

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:10<00:00,  1.26s/it]

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "wenda.py", line 201, in load_model
    LLM.load_model()
  File "/root/glm/wenda/plugins/llm_glm6b.py", line 39, in load_model
    device, precision = settings.glm_strategy.split()
ValueError: not enough values to unpack (expected 2, got 1)```

请问为什么会报这个错

**Comment by Midnight-719** [comment]
你知道是什么问题了么
