### ISSUE TITLE
Bug report:UnicodeDecodeError  when running  "run_data_processing.bat"

### ISSUE THREAD

**Issue by Pythonpa** [l15y/wenda#14]
感谢作者的付出，赛博菩萨。
一、问题背景：使用的新版的集成包，准备了一个txt文档，且下载好了“simcse-chinese-roberta-wwm-ext”放入models文件夹，想让其构建知识库。
二、问题描述：按照项目运行说明，运行"run_data_processing.bat"文件，出现如下编码格式报错信息：

embeddings模型地址 model\simcse-chinese-roberta-wwm-ext
vectorstore保存地址 xw
Traceback (most recent call last):
  File "D:\pythonProject\wenda\gen_data.py", line 20, in <module>
    data = f.read()
  File "D:\pythonProject\wenda\WPy64-31090\python-3.10.9.amd64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "D:\pythonProject\wenda\WPy64-31090\python-3.10.9.amd64\lib\encodings\utf_16.py", line 61, in _buffer_decode
    codecs.utf_16_ex_decode(input, errors, 0, final)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 192-193: illegal UTF-16 surrogate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonProject\wenda\gen_data.py", line 23, in <module>
    data = f.read()
  File "D:\pythonProject\wenda\WPy64-31090\python-3.10.9.amd64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 81: invalid continuation byte
请按任意键继续. . .

**Comment by l15y** [comment]
说明你的文件不是UTF-16或UTF-8编码。
目前我只做了这两种尝试。
你可以手动另存为UTF-8
