### ISSUE TITLE
Linux: fess 运行失败

### ISSUE THREAD

**Issue by wangfh5** [l15y/wenda#145]
环境: WSL2

`java -version`输出正常, 下载好fess-14.7.0后解压, 进入bin文件夹, 然后运行 `~/fess`报错

```
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:65)
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81)
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:137)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:272)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:253)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4609)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5248)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:430)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:713)
        at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:402)
        at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:347)
        at org.codelibs.fess.FessBoot.main(FessBoot.java:111)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.SearchEngineClient, because org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        ... 42 more
Caused by: org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:526)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:378)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:311)
        at org.codelibs.fess.es.client.SearchEngineClient.open(SearchEngineClient.java:305)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49)
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59)
        ... 49 more
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/home/wangfh5/AIGC_projects/fess-14.7.0/es/node_1/data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:341)
        at org.opensearch.node.Node.<init>(Node.java:464)
        at org.codelibs.opensearch.runner.node.OpenSearchRunnerNode.<init>(OpenSearchRunnerNode.java:31)
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:520)
        ... 58 more
```

启动闻达, bing模式正常使用. 启动 fess 模式, 无法搜索到本地知识库内容. 
![image](https://user-images.githubusercontent.com/51868839/232315925-2354e715-4abb-466b-8326-5ab1ce54ea62.png)

**Comment by tron19920125** [comment]
碰到一样的问题
`org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml
* * * * * * * * * */
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:65)
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81)
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:137)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:272)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:253)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4609)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5248)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:430)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:713)
        at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:402)
        at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:347)
        at org.codelibs.fess.FessBoot.main(FessBoot.java:111)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.SearchEngineClient, because org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        ... 42 more
Caused by: org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:526)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:378)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:311)
        at org.codelibs.fess.es.client.SearchEngineClient.open(SearchEngineClient.java:305)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49)
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59)
        ... 49 more
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/home/notebook/data/personal/coding/gpt/chatglm-6b/wenda/fess-14.7.0-with-jdk/es/node_1/data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:341)
        at org.opensearch.node.Node.<init>(Node.java:464)
        at org.codelibs.opensearch.runner.node.OpenSearchRunnerNode.<init>(OpenSearchRunnerNode.java:31)
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:520)
        ... 58 more`

**Comment by tron19920125** [comment]
碰到一样的问题
`
org.lastaflute.di.exception.ContainerInitFailureException: Look! Read the message below.

Failed to initialize the container.

[Path]
esclient.xml

[Namespace]
null

[Included by]
esflute_config.xml
esflute_user.xml
esflute_log.xml

        at org.lastaflute.di.core.meta.impl.LaContainerImpl.throwContainerInitFailureException(LaContainerImpl.java:463)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:415)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:431)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        at org.lastaflute.di.core.factory.SingletonLaContainerFactory.init(SingletonLaContainerFactory.java:65)
        at org.lastaflute.web.container.WebLastaContainerInitializer.doInitContainer(WebLastaContainerInitializer.java:81)
        at org.lastaflute.web.container.WebLastaContainerInitializer.initialize(WebLastaContainerInitializer.java:45)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.initializeContainer(LastaPrepareFilter.java:137)
        at org.lastaflute.web.servlet.filter.LastaPrepareFilter.init(LastaPrepareFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:272)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:253)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4609)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5248)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:265)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:430)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486)
        at org.dbflute.tomcat.TomcatBoot.startServer(TomcatBoot.java:713)
        at org.dbflute.tomcat.TomcatBoot.go(TomcatBoot.java:402)
        at org.dbflute.tomcat.TomcatBoot.bootAwait(TomcatBoot.java:347)
        at org.codelibs.fess.FessBoot.main(FessBoot.java:111)
Caused by: org.lastaflute.di.core.exception.IllegalMethodRuntimeException: [ESSR0060]Can not configure method(open) of org.codelibs.fess.es.client.SearchEngineClient, because org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:61)
        at org.lastaflute.di.core.assembler.DefaultInitMethodAssembler.assemble(DefaultInitMethodAssembler.java:40)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.assemble(SingletonComponentDeployer.java:57)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.deploy(SingletonComponentDeployer.java:41)
        at org.lastaflute.di.core.deployer.SingletonComponentDeployer.init(SingletonComponentDeployer.java:35)
        at org.lastaflute.di.core.meta.impl.ComponentDefImpl.init(ComponentDefImpl.java:85)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.doInit(LaContainerImpl.java:434)
        at org.lastaflute.di.core.meta.impl.LaContainerImpl.init(LaContainerImpl.java:413)
        ... 42 more
Caused by: org.codelibs.opensearch.runner.OpenSearchRunnerException: Failed to start node 1
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:526)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:378)
        at org.codelibs.opensearch.runner.OpenSearchRunner.build(OpenSearchRunner.java:311)
        at org.codelibs.fess.es.client.SearchEngineClient.open(SearchEngineClient.java:305)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.lastaflute.di.util.LdiMethodUtil.invoke(LdiMethodUtil.java:49)
        at org.lastaflute.di.core.assembler.AbstractMethodAssembler.invoke(AbstractMethodAssembler.java:59)
        ... 49 more
Caused by: java.lang.IllegalStateException: failed to obtain node locks, tried [[/home/notebook/data/personal/coding/gpt/chatglm-6b/wenda/fess-14.7.0-with-jdk/es/node_1/data]] with lock id [0]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [1])?
        at org.opensearch.env.NodeEnvironment.<init>(NodeEnvironment.java:341)
        at org.opensearch.node.Node.<init>(Node.java:464)
        at org.codelibs.opensearch.runner.node.OpenSearchRunnerNode.<init>(OpenSearchRunnerNode.java:31)
        at org.codelibs.opensearch.runner.OpenSearchRunner.execute(OpenSearchRunner.java:520)
        ... 58 more
`

**Comment by RuiShaoo** [comment]
请问解决了吗？ @tron19920125 @wangfh5

**Comment by tron19920125** [comment]
> 请问解决了吗？ @tron19920125 @wangfh5

没有解决，我临时用其他解决方案去了，等git主更新再看看

**Comment by l15y** [comment]
用不了没事，用最新的st
