### ISSUE TITLE
cannot run with RWKV_CUDA_ON =1

### ISSUE THREAD

**Issue by oddwatcher** [l15y/wenda#146]
**Describe the bug**
Set RWKV_CUDA_ON =1, installed ninja in the environment with pip, and run run_rwkv.bat in x64 Native Tools Command Prompt for Visual Studio 2022, the kernel is compiled and is present but won't load.
Also tried to set pyTorch's extension path to a path under the environment, but wont work.

**Expected behavior**

WebUI 端口号 17860
LLM模型类型 rwkv
rwkv模型地址 model\RWKV-4-Raven-7B-v9-8.5E-1,0C-0.4Multi-20230414-ctx4096.pth
rwkv模型参数 cuda fp16i8
日志记录 True
知识库类型 rh
知识库显示来源 True
知识库融合参数 fess:2 bing:5
chunk_size 200
chunk_count 5
知识库文件夹名称为: zsk
['fess', '2']
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
Using D:\Wenda-Chat\wenda\\WPy64-38100\python-3.8.10.amd64\pyTorch as PyTorch extensions root...
D:\Wenda-Chat\wenda\plugins\textrank4zh\Segmentation.py:37: ResourceWarning: unclosed file <_io.BufferedReader name='D:\\Wenda-Chat\\wenda\\plugins\\textrank4zh\\stopwords.txt'>
  for word in codecs.open(self.stop_words_file, 'r', 'utf-8', 'ignore'):
ResourceWarning: Enable tracemalloc to get the object allocation traceback
['bing', '5']
 知识库加载完成
Detected CUDA files, patching ldflags
Emitting ninja build file D:\Wenda-Chat\wenda\\WPy64-38100\python-3.8.10.amd64\pyTorch\wkv_cuda\build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module wkv_cuda...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "wenda.py", line 201, in load_model
    LLM.load_model()
  File "D:\Wenda-Chat\wenda\plugins\llm_rwkv.py", line 100, in load_model
    from rwkv.model import RWKV  # pip install rwkv
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\rwkv\model.py", line 29, in <module>
    load(
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\torch\utils\cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\torch\utils\cpp_extension.py", line 1934, in _import_module_from_library
    torch.ops.load_library(filepath)
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\Wenda-Chat\wenda\WPy64-38100\python-3.8.10.amd64\pyTorch\wkv_cuda\wkv_cuda.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by oddwatcher** [comment]
Solving this problem is very worthy because it could enable lots of users with 8 gig vram to use charRWKV with 7B full potential.

**Comment by diannaojiang** [comment]
Cannot run rwkv in compile mode, please build your own environment and consult the chatrwkv community.

**Comment by l15y** [comment]
可以去rwkv官方项目看看

**Comment by BlinkDL** [comment]
@oddwatcher @diannaojiang 

### Note RWKV_CUDA_ON will build a CUDA kernel ("pip install ninja" first).

### How to build in Linux: set these and run v2/chat.py
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

### How to build in win:
Install VS2022 build tools (https://aka.ms/vs/17/release/vs_BuildTools.exe select Desktop C++). Reinstall CUDA 11.7 (install VC++ extensions). Run v2/chat.py in "x64 native tools command prompt".

**Comment by oddwatcher** [comment]
Yep, fixed it with reinstalling CUDA11.7, looks like this problem is because using CUDA 12.1. Also, looks like manually pointing a PATH to the location of cl.exe (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64) is also working without having to use x64 native tools command prompt.
