### ISSUE TITLE
用18日的懒人包 使用bingsite模式，提示以下错误。

### ISSUE THREAD

**Issue by wukenny11111** [l15y/wenda#161]
Exception happened during processing of request from ('127.0.0.1', 52042)
Traceback (most recent call last):
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\paste\httpserver.py", line 1092, in process_request_in_thread
    self.finish_request(request, client_address)
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\paste\httpserver.py", line 460, in handle
    BaseHTTPRequestHandler.handle(self)
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\paste\httpserver.py", line 455, in handle_one_request
    self.wsgi_execute()
  File "D:\wenda1\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\paste\httpserver.py", line 307, in wsgi_execute
    for chunk in result:
  File "wenda.py", line 229, in api_chat_stream
    response_d = zhishiku.find(keyword)
  File "D:\wenda1\wenda\plugins\zhishiku_bingsite.py", line 17, in find
    url = 'https://cn.bing.com/search?q={}'.format(search_query)+" site:"+os.environ.get('site')
TypeError: can only concatenate str (not "NoneType") to str

在config.xml保留了默认的www.12371.cn，但是一直还有问题
----------------------------------------

**Comment by l15y** [comment]
要自己写配置xml，一直没做

**Comment by wukenny11111** [comment]
> 要自己写配置xml，一直没做

没太理解？按文档说明只要保留一个网站地址不是就可以了么？

**Comment by l15y** [comment]
要自己做个bingsite的项

**Comment by wukenny11111** [comment]
> 不使用bing site，用bing 不就解決了嗎？ (自行安裝的最新版，config.xml也沒有了bing site 的建議選項；暫時不管他吧)

感谢回复，但是bing搜索的内容不可控，有了site相对来说范围缩小了，可控性更高。希望作者能早日支持

**Comment by l15y** [comment]
已修复
