### ISSUE TITLE
zhishiku has no attribute 'find'

### ISSUE THREAD

**Issue by tomsux** [l15y/wenda#164]
Traceback (most recent call last):
  File "/home/zyh/ai/py38/langchain/lib/python3.8/site-packages/paste/httpserver.py", line 1092, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/home/zyh/ai/py38/langchain/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/zyh/ai/py38/langchain/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/zyh/ai/py38/langchain/lib/python3.8/site-packages/paste/httpserver.py", line 460, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/home/zyh/ai/py38/langchain/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/zyh/ai/py38/langchain/lib/python3.8/site-packages/paste/httpserver.py", line 455, in handle_one_request
    self.wsgi_execute()
  File "/home/zyh/ai/py38/langchain/lib/python3.8/site-packages/paste/httpserver.py", line 307, in wsgi_execute
    for chunk in result:
  File "wenda.py", line 237, in api_chat_stream
    response_d = zhishiku.find(keyword)
AttributeError: 'NoneType' object has no attribute 'find'
----------------------------------------

**Comment by l15y** [comment]
按照文档正确配置环境
