### ISSUE TITLE
運行 build_qdrant_data.bat 時報錯

### ISSUE THREAD

**Issue by kiron111** [l15y/wenda#167]
**Describe the bug**
運行 build_qdrant_data.bat 時報錯︰

Traceback (most recent call last):
  File "F:\wenda\plugins\gen_data_qdrant.py", line 28, in <module>
    source_folder = settings.library.qdrant.Path
AttributeError: 'obj' object has no attribute 'qdrant'
Press any key to continue . . .

**Desktop (please complete the following information):**
 - OS: Win11
 - Anaconda Python 3.10.9

我從github 安裝(不是懶人包)，
已執行 pip install -r requirements-qdrant.txt

我也安裝了其餘的倚賴，其他功能是沒問題的

**Comment by kiron111** [comment]
對不起，我沒理解清楚，
是改那一個選項？
有幾個模式選擇？(我要trial and error 地試試)

**Comment by kiron111** [comment]
我試著把config.xml 的cpu 改成cuda, 也是同樣的報錯

**Comment by kiron111** [comment]
知道了

我把模式轉為qdrant，沒有以上報錯，
運行到 qdrant_data.bat，但出現另一種報錯


Collection qa_collection is successfully created.
Traceback (most recent call last):
  File "C:\Users\kxxxb\anaconda3\lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\kxxxb\anaconda3\lib\site-packages\httpcore\backends\sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
  File "C:\Users\kxxxb\anaconda3\lib\socket.py", line 845, in create_connection
    raise err
  File "C:\Users\kxxxb\anaconda3\lib\socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by l15y** [comment]
似乎没有链接上qdart

**Comment by kiron111** [comment]
我排查不到問題，等下一個懶人包吧 :-)

**Comment by l15y** [comment]
懒人包不会做这个
