### ISSUE TITLE
【依赖repo需要rebase】MAC M1 llama.cpp 模型加载报错

### ISSUE THREAD

**Issue by yhyu13** [l15y/wenda#189]
**Describe the bug**
Mac M1 llama.cpp 加载出错，
客户端运行，但是因为没有模型，所以对话没有反应

**To Reproduce**
Mac M1
torch nightly build
本地编译 readme中的llama-cpp-python 0.1.33
text2vec-large-chinese拉取https://huggingface.co/GanymedeNil/text2vec-large-chinese/tree/main
./run_llama.sh

**Expected behavior**
模型正常加载

**Screenshots**
```
(wenda) hangyu5@hangyu5deMac-mini wenda % 
(wenda) hangyu5@hangyu5deMac-mini wenda % cp /Users/hangyu5/Documents/git-repoMy/AIResearchVault/repo/LLMApp/text-generation-webui/models/ggml-vicuna-7b-1.0-uncensored-q4_0.bin ./model 
(wenda) hangyu5@hangyu5deMac-mini wenda % ./run_llama.sh                                                                                                                                
Namespace(Config='config.xml', Port=None, Logging=None, LLM_Type='llama')

    Logging: False
    Port: 17860
    LLM_Type: llama
    Path: model/ggml-vicuna-7b-1.0-uncensored-q4_0.bin
    Strategy: null
    Api_key: null
    Public_key: null
    library: 
        Type: bing
        Show_Soucre: False
        Size: 200
        Step: 2
        bing: 
            Count: 5
            Academic: True
            Searc_Site: www.12371.cn
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
    self.run()
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hangyu5/Documents/git-repoMy/AIResearchVault/repo/LLMApp/wenda/wenda.py", line 287, in load_model
    LLM.load_model()
  File "/Users/hangyu5/Documents/git-repoMy/AIResearchVault/repo/LLMApp/wenda/plugins/llm_llama.py", line 34, in load_model
    from llama_cpp import Llama
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/site-packages/llama_cpp_python-0.1.33-py3.10-macosx-13.0-arm64.egg/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/site-packages/llama_cpp_python-0.1.33-py3.10-macosx-13.0-arm64.egg/llama_cpp/llama_cpp.py", line 184, in <module>
    _lib.llama_get_kv_cache.argtypes = [llama_context_p]
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/hangyu5/anaconda3/envs/wenda/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x8854e0d0, llama_get_kv_cache): symbol not found
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
知识库加载完成
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
```

**Comment by yhyu13** [comment]
是不是llama-cpp-python版本太老了，最新已经0.1.38了

**Comment by yhyu13** [comment]
@l15y 
你的llamacpppython fork
git pull --rebase https://github.com/abetlen/llama-cpp-python.git main
之后安装，升级到了0.1.38版本，就能够成功加载，
Mac mini 16G M1 7B模型，差不多10t/s

**Comment by yhyu13** [comment]
这个 https://github.com/abetlen/llama-cpp-python.git
也是有毒，用的居然是ssh git :)

**Comment by yhyu13** [comment]
![截屏2023-04-25 17 22 24](https://user-images.githubusercontent.com/19365678/234233381-1b3c0b35-1894-4290-9744-27aaf6e7cb4b.png)

这个中文是正常的吗？感觉怪怪的，还是vicuña本身的问题？

**Comment by l15y** [comment]
反正我是感觉这玩意中文有点弱。不过看起来官方的已经支持中文，那也没必要再用我的fork了
