### ISSUE TITLE
【bug？】重启项目后，显示如下错误？

### ISSUE THREAD

**Issue by adogshz** [l15y/wenda#19]
设备配置为：32g 内存，3080 16g 显卡，系统为win11 企业版 22h2 
运行包为：懒人版
重启运行后第一遍无任何问题，ctrl+c中断退出后，再次运行，出现如下错误：
D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn(
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on http://127.0.0.1:17860
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\pub\wenda\GLM6BAPI.py", line 144, in load_model
    model = AutoModel.from_pretrained(glm_path, local_files_only=True, trust_remote_code=True)
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\adogs/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 927, in __init__    self.lm_head = skip_init(
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "D:\pub\wenda\WPy64-31090\python-3.10.9.amd64\lib\site-packages\torch\_refs\__init__.py", line 4254, in empty_like
    return torch.empty_strided(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1069285376 bytes.

**Comment by l15y** [comment]
显然前一实例未关闭完成显存不足
