### ISSUE TITLE
1060 6G的显卡能不能跑？

### ISSUE THREAD

**Issue by wwjCMP** [l15y/wenda#214]
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "wenda.py", line 287, in load_model
    LLM.load_model()
  File "D:\BaiduNetdiskDownload\wenda\plugins\llm_glm6b.py", line 31, in load_model
    model = AutoModel.from_pretrained(
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\transformers\modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1034, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1409, in quantize
    self.transformer = quantize(self.transformer, bits, use_quantization_cache=use_quantization_cache, empty_init=empty_init, **kwargs)
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 448, in quantize
    layer.attention.query_key_value = QuantizedLinearWithPara(
  File "C:\Users\wwj93/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 301, in __init__
    super(QuantizedLinear, self).__init__(*args, **kwargs)
  File "D:\BaiduNetdiskDownload\wenda\WPy64-38100\python-3.8.10.amd64\lib\site-packages\torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
RuntimeError: [enforce fail at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 201326592 bytes.

**Comment by l15y** [comment]
能

**Comment by wwjCMP** [comment]
> 能
RuntimeError: [enforce fail at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 201326592 bytes. 出现这个报错是什么原因？有没有办法解决

**Comment by wwjCMP** [comment]
> 能

RuntimeError: [enforce fail at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 201326592 bytes. 出现这个报错是什么原因？有没有办法解决

**Comment by l15y** [comment]
加虚拟内存
