### ISSUE TITLE
懒人包还是不够懒_(:3_/ 出现了好多看不懂的报错

### ISSUE THREAD

**Issue by minlo-18** [l15y/wenda#228]
Namespace(Config='config.xml', Port=None, Logging=None, LLM_Type='glm6b')

    Logging: False
    Port: 17860
    LLM_Type: glm6b
    Path: model/chatglm-6b-int4
    Strategy: cuda fp16
    Lora: null
    library:
        Type: mix
        Show_Soucre: False
        Step: 2
        mix:
            Strategy: rtst:2 bingsite:2 bing:2
            Count: 5
        rtst:
            Count: 2
            Model_Path: model/text2vec-large-chinese
            Device: cpu
        bingsite:
            Count: 2
            site: www.12371.cn
        bing:
            Count: 2
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
C:\Users\admin/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py:1259: DeprecationWarning: invalid escape sequence '\?'
  ["\?", "？"],
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\wd-git\wenda\wenda.py", line 289, in load_model
    LLM.load_model()
  File "C:\Users\admin\Desktop\wd-git\wenda\plugins\llm_glm6b.py", line 31, in load_model
    model = AutoModel.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\modeling_utils.py", line 2164, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory model/chatglm-6b-int4.
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:1049: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
No sentence-transformers model found with name model/text2vec-large-chinese. Creating a new one with MEAN pooling.
embedding加载失败，请下载相应模型
知识库加载失败，请阅读说明
Exception in thread Thread-2 (load_zsk):
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\admin\Desktop\wd-git\wenda\wenda.py", line 306, in load_zsk
    raise e
  File "C:\Users\admin\Desktop\wd-git\wenda\wenda.py", line 302, in load_zsk
    zhishiku = import_module('plugins.zhishiku_'+settings.library.Type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\wd-git\wenda\plugins\zhishiku_mix.py", line 8, in <module>
    zhishiku = import_module('plugins.zhishiku_'+item[0])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\admin\Desktop\wd-git\wenda\plugins\zhishiku_rtst.py", line 71, in <module>
    raise e
  File "C:\Users\admin\Desktop\wd-git\wenda\plugins\zhishiku_rtst.py", line 67, in <module>
    embeddings.client = sentence_transformers.SentenceTransformer(cunnrent_setting.Model_Path,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 97, in __init__
    modules = self._load_auto_model(model_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 806, in _load_auto_model
    transformer_model = Transformer(model_name_or_path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\models\Transformer.py", line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\sentence_transformers\models\Transformer.py", line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\models\auto\auto_factory.py", line 464, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Desktop\wd-git\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\transformers\modeling_utils.py", line 2164, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory model/text2vec-large-chinese.

**Comment by l15y** [comment]
embedding加载失败，请下载相应模型
知识库加载失败，请阅读说明
