### ISSUE TITLE
请教一下，默认知识库构建发生错误

### ISSUE THREAD

**Issue by dream-desktop** [l15y/wenda#241]
错误信如下；

Embedding 加载完成
文件列表生成完成 0
处理完成
新建索引
Traceback (most recent call last):
  File "E:\tensorflow-learning\github\wenda-webui\wenda\plugins\gen_data_st.py", line 122, in <module>
    vectorstore_old = FAISS.load_local(
                      ^^^^^^^^^^^^^^^^^
  File "E:\tensorflow-learning\github\wenda-webui\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\vectorstores\faiss.py", line 466, in load_local
    index = faiss.read_index(
            ^^^^^^^^^^^^^^^^^
  File "E:\tensorflow-learning\github\wenda-webui\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\faiss\swigfaiss.py", line 9795, in read_index
    return _swigfaiss.read_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open memory\default\index.faiss for reading: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tensorflow-learning\github\wenda-webui\wenda\plugins\gen_data_st.py", line 129, in <module>
    vectorstore.save_local('memory/default')
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'save_local'
Press any key to continue . . .

**Comment by tpoisonooo** [comment]
新建一个 txt 目录，里面随便放点文本。这个地方没做 None 处理。

**Comment by dream-desktop** [comment]
> 新建一个 txt 目录，里面随便放点文本。这个地方没做 None 处理。
感谢！
