### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.model/chatglm-6b'

### ISSUE THREAD

**Issue by RougeWhite** [l15y/wenda#262]
```
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\software\Anaconda\envs\ChatMPT\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\software\Anaconda\envs\ChatMPT\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "F:\Python\wd-git\wenda\wenda.py", line 44, in load_model
    LLM.load_model()
  File "F:\Python\wd-git\wenda\llms\llm_glm6b.py", line 66, in load_model
    tokenizer = AutoTokenizer.from_pretrained(
  File "D:\software\Anaconda\envs\ChatMPT\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 686, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "D:\software\Anaconda\envs\ChatMPT\lib\site-packages\transformers\dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\software\Anaconda\envs\ChatMPT\lib\site-packages\transformers\dynamic_module_utils.py", line 157, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\software\Anaconda\envs\ChatMPT\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.model/chatglm-6b'
No sentence-transformers model found with name model/text2vec-large-chinese. Creating a new one with MEAN pooling.
知识库加载完成
```

config.yml
```

logging: False
#日志"
port: 17860
#webui 默认启动端口号"
library: 
     strategy: "sogowx:3 bingsite:2 rtst:2 agents:0"
     #知识库参数，每组参数间用空格分隔，冒号前为知识库类型，后为抽取数量。

     #知识库类型:
     #bing        cn.bing搜索，仅国内可用，目前处于服务降级状态
     #sosowx      sogo微信公众号搜索，可配合相应auto实现全文内容分析
     #fess        fess搜索引擎
     #rtst        支持实时生成的sentence_transformers
     #remote      调用远程闻达知识库，用于集群化部署
     #kg          知识图谱,暂未启用
     #特殊库：
     #mix         根据参数进行多知识库融合
     #agents      提供网络资源代理，没有知识库查找功能，所以数量为0
     #            （目前stable-diffusion的auto脚本需要使用其中功能，同时需开启stable-diffusion的api功能）

     count: 5
     #最大抽取数量（所有知识库总和）

     show_soucre: true
     #知识库显示来源

     step: 2
     #知识库默认上下文步长
librarys: 
  bing: 
    count: 5
     #最大抽取数量
  bingsite: 
     count: 5
     #最大抽取数量
     site: "cn.bing.com"
     #搜索网站
  fess: 
     count: 1
     #最大抽取数量
     fess_host: "127.0.0.1:8080"
     #fess搜索引擎的部署地址
  remote: 
    host: "http://127.0.0.1:17860/api/find"
     #远程知识库地址地址
  rtst: 
     count: 3
     #最大抽取数量
     size: 20
     #分块大小"
     overlap: 0
     #分块重叠长度
     model_path: "model/text2vec-large-chinese"
     #向量模型存储路径
     device: cuda
     #embedding运行设备
  qdrant: 
     path: txt
     #知识库文本路径
     model_path: "model/text2vec-large-chinese"
     #向量模型存储路径
     qdrant_host: "http://localhost:6333"
     #qdrant服务地址"
     device: cuda
     #qdrant运行设备
     collection: qa_collection
     #qdrant集合名称
  kg: 
     count: 5
     #最大抽取数量
     knowledge_path: ""
     #知识库的文件夹目录名称，若留空则为txt
     graph_host: ""
     #图数据库部署地址
     model_path: ""
     #信息抽取模型所在路径"
llm_type: glm6b
#llm模型类型:glm6b、rwkv、llama、replitcode等，详见相关文件
llm_models: 
  rwkv: 
     path: "model/rwkv-4-raven-7b-v11.pth"      #rwkv模型位置"
     strategy: "cuda fp16i8"
   #   path: "model/rwkv_ggml_q8.bin"           #rwkv模型位置"
   #   strategy: "Q8_0"       #rwkvcpp:运行方式，设置strategy诸如"Q8_0->16"即可开启，代表运行Q8_0模型在16个cpu核心上
     #rwkv模型参数"
    
     historymode: state
     #rwkv历史记录实现方式：state、string
  glm6b: 
     path: "model/chatglm-6b"
     #glm模型位置"
     strategy: "cuda fp16i8"
     #cuda fp16	 所有glm模型 要直接跑在gpu上都可以使用这个参数
     #cuda fp16i8	 fp16原生模型 要自行量化为int8跑在gpu上可以使用这个参数
     #cuda fp16i4	 fp16原生模型 要自行量化为int4跑在gpu上可以使用这个参数
     #cpu fp32	 所有glm模型 要直接跑在cpu上都可以使用这个参数
     #cpu fp16i8	fp16原生模型 要自行量化为int8跑在cpu上可以使用这个参数
     #cpu fp16i4	fp16原生模型要 自行量化为int4跑在cpu上可以使用这个参数"
     #cuda:0 fp16 *14 -> cuda:1	fp16 多卡流水线并行，使用方法参考RWKV的strategy介绍。总层数28
     lora: ""
     #glm-lora模型位置
  llama: 
     path: "model/stable-vicuna-13B.ggml.q4_2.bin"
     #llama模型位置
     strategy: ""
     #llama模型参数 暂时不用
  moss: 
     path: "model/moss-moon-003-sft-plugin-int4"
     #模型位置
     strategy: ""
     #模型参数 暂时不用"
  replitcode: 
     path: "model/replit-code-v1-3b"
     #replitcode模型位置
     #说明：目前模型参数和chat模型差异较大，写死了，不能通过wenda界面配置，需要调整自行到llm_replitcode.py 文件中调整，或放开wenda界面参数
     #y = model.generate(x, max_length=100, do_sample=true, top_p=0.95, top_k=4, temperature=0.2, num_return_sequences=1, eos_token_id=tokenizer.eos_token_id)
     #模型地址：https://huggingface.co/replit/replit-code-v1-3b ，约10g
     #作用代码补全：问：def fibonacci(n):
     #答：def fibonacci(n):
     #if n == 0:
     #return 0
     #elif n == 1:
     #return 1
     #else:
     #return fibonacci(n-1) + fibonacci(n-2)
     #print(fibonacci(10))
     strategy: "cuda fp16"
    #因我的3070只有8g内存，所以是先把模理加载到内存进行精度转换，至少要32g系统内存， fp16 占用不到6g显存,fp32 超过8g未测试"
```

**Comment by l15y** [comment]
transformers版本问题。多换几个试试。
另外这个问题应该去找智谱，与wenda无关
