### ISSUE TITLE
 'gbk' codec can't decode byte 0xd1 in position 253: illegal multibyte sequence

### ISSUE THREAD

**Issue by xain** [l15y/wenda#277]
读取中文pdf时出现，试了很多个都这类似，英文pdf没有问题。

```
文件读取失败，当前文件已被跳过： 城发环境：2018年年度报告.PDF 。错误信息： 'gbk' codec can't decode byte 0xd1 in position 253: illegal multibyte sequence
Exception in thread Thread-1 (clac_embedding):
Traceback (most recent call last):
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\wenda\plugins\gen_data_st.py", line 53, in clac_embedding
    vectorstore_new = FAISS.from_texts(texts, embeddings, metadatas=metadatas)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\vectorstores\faiss.py", line 385, in from_texts
    return cls.__from(
           ^^^^^^^^^^^
  File "C:\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\langchain\vectorstores\faiss.py", line 347, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
                                  ~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by l15y** [comment]
PDF 换成小写才会识别

**Comment by xain** [comment]
你说的很对，我昨天晚上瞎弄了一晚上。已经提交修正代码pr。

**Comment by xain** [comment]
#281
