### ISSUE TITLE
使用cuda加速rwkv模型遇到报错：RuntimeError: Error building extension 'wkv_cuda'

### ISSUE THREAD

**Issue by shmily91** [l15y/wenda#278]
1、按要求安装了vs（安装了C++）、cuda
2、torch 2.0  cuda（True），可用
3、模型rwkv-7b 10v
4、显卡3090
5、pip 安装了 rwkv ninja
6、参数没有改动

serving on 0.0.0.0:17860 view at http://127.0.0.1:17860
No sentence-transformers model found with name model/text2vec-large-chinese. Creating a new one with MEAN pooling.
Using C:\Users\DJS\AppData\Local\torch_extensions\torch_extensions\Cache\py311_cu118 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\DJS\AppData\Local\torch_extensions\torch_extensions\Cache\py311_cu118\wkv_cuda\build.ninja...
Building extension module wkv_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: 'L:/BaiduNetdiskDownload/�½��ļ���/wenda512/wenda/WPy64-31110/python-3.11.1.amd64/Lib/site-packages/rwkv/cuda/wrapper.cpp', needed by 'wrapper.o', missing and no known rule to make it
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\wenda.py", line 44, in load_model
    LLM.load_model()
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\llms\llm_rwkv.py", line 262, in load_model
    from rwkv.model import RWKV  # pip install rwkv
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\rwkv\model.py", line 29, in <module>
    load(
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\torch\utils\cpp_extension.py", line 1284, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\torch\utils\cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\torch\utils\cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "L:\BaiduNetdiskDownload\新建文件夹\wenda512\wenda\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\torch\utils\cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'wkv_cuda'

RuntimeError: Error building extension 'wkv_cuda'  这个问题我该怎么修复

**Comment by l15y** [comment]
先试试换成英文路径

**Comment by shmily91** [comment]
解决了，原来时设置显卡的问题

**Comment by shmily91** [comment]
我把run_rwkv_with_vc.bat文件中     set RWKV_CUDA_ON=1 改成=0就可以了

**Comment by shmily91** [comment]
> 先试试换成英文路径
我按你说的改了路径 set RWKV_CUDA_ON=1 可以用了，谢谢大师神

**Comment by Aqual-lu** [comment]
> 我把run_rwkv_with_vc.bat文件中 set RWKV_CUDA_ON=1 改成=0就可以了

请问这个run_rwkv_with_vc.bat在哪里呀?
