### ISSUE TITLE
错误！

### ISSUE THREAD

**Issue by eastgold15** [l15y/wenda#33]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Exception in thread Thread-1 (load_model):
Traceback (most recent call last):
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "X:\wenda.7z\GLM6BAPI.py", line 144, in load_model
    model = AutoModel.from_pretrained(glm_path, local_files_only=True, trust_remote_code=True)
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\1/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 940, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\1/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1262, in quantize
    from .quantization import quantize, QuantizedEmbedding, QuantizedLinear, load_cpu_kernel
  File "C:\Users\1/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 13, in <module>
    from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\__init__.py", line 1, in <module>
    from . import library
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\library\__init__.py", line 1, in <module>
    from . import nvrtc
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\library\nvrtc.py", line 5, in <module>
    nvrtc = Lib("nvrtc")
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\library\base.py", line 45, in __init__
    lib_path = windows_find_lib(self.__name)
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\library\base.py", line 39, in windows_find_lib
    return lookup_dll(lib_name)
  File "X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\cpm_kernels\library\base.py", line 16, in lookup_dll
    for name in os.listdir(path):
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\Users\\1\\AppData\\Local\\Programs\\Python\\Python311\\python.exe'
X:\wenda.7z\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn(
<frozen importlib._bootstrap>:914: ImportWarning: _ImportRedirect.find_spec() not found; falling back to find_module()
serving on http://127.0.0.1:17860

**Comment by l15y** [comment]
没有读到模型
另外你用的是旧版，建议先更新

**Comment by baltam** [comment]
> 没有读到模型 另外你用的是旧版，建议先更新

怎么看出来那些是旧版，4.5是新版还是旧版呢

**Comment by l15y** [comment]
NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\Users\1\AppData\Local\Programs\Python\Python311\python.exe'
这个应该是你自己改了什么东西？
