### ISSUE TITLE
run_data出错。

### ISSUE THREAD

**Issue by newhuman011** [l15y/wenda#34]
webui能够正常使用。

glm模型地址 G:\ChatGLM\WENDAglm\wenda\model\chatglm-6b
rwkv模型地址 ..\RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth
rwkv模型参数 cuda fp16i8 *18+
日志记录 True
chunk_size 100
chunk_count 3
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\69030\AppData\Local\Temp\jieba.cache
Loading model cost 0.516 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "G:\ChatGLM\WENDAglm\wenda\gen_data.py", line 23, in <module>
    data = f.read()
  File "G:\ChatGLM\WENDAglm\wenda\WPy64-31090\python-3.10.9.amd64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "G:\ChatGLM\WENDAglm\wenda\WPy64-31090\python-3.10.9.amd64\lib\encodings\utf_16.py", line 61, in _buffer_decode
    codecs.utf_16_ex_decode(input, errors, 0, final)
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 88-89: illegal encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ChatGLM\WENDAglm\wenda\gen_data.py", line 26, in <module>
    data = f.read()
  File "G:\ChatGLM\WENDAglm\wenda\WPy64-31090\python-3.10.9.amd64\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 3: invalid continuation byte
请按任意键继续. . .

**Comment by l15y** [comment]
你的txt文件，用的应该是gbk编码
