### ISSUE TITLE
能否在colab中运行

### ISSUE THREAD

**Issue by jessdy** [l15y/wenda#35]
我尝试使用colab运行此项目

```
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/
!git clone https://github.com/l15y/wenda

# 安装依赖
%cd /content/drive/MyDrive/wenda
!pip install -r requirements.txt
%mkdir /content/drive/MyDrive/wenda/model
%cd /content/drive/MyDrive/wenda/model
!git lfs install
!git clone https://huggingface.co/THUDM/chatglm-6b-int4

%cd /content/drive/MyDrive/wenda
!chmod +x run_GLM6B.sh
!./run_GLM6B.sh
```

但是报错了
```
/content/drive/MyDrive/wenda
glm模型地址 model/chatglm-6b-int4
rwkv模型地址 model/RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth
rwkv模型参数 cuda fp16i8 *18+
日志记录 True
chunk_size 200
chunk_count 1
Traceback (most recent call last):
  File "/content/drive/MyDrive/wenda/GLM6BAPI.py", line 141, in <module>
    import zhishiku
  File "/content/drive/MyDrive/wenda/zhishiku.py", line 5, in <module>
    ix = storage.open_index()
  File "/usr/local/lib/python3.9/dist-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/usr/local/lib/python3.9/dist-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python3.9/dist-packages/whoosh/index.py", line 618, in read
    raise EmptyIndexError("Index %r does not exist in %r"
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('sy')
2023-04-08 11:35:16.730034: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-08 11:35:17.027958: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-08 11:35:18.109132: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/wenda/GLM6BAPI.py", line 130, in load_model
    from transformers import AutoModel, AutoTokenizer
  File "/usr/local/lib/python3.9/dist-packages/transformers/__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "/usr/local/lib/python3.9/dist-packages/transformers/dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/usr/local/lib/python3.9/dist-packages/transformers/utils/generic.py", line 33, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 31, in <module>
    from . import compat
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 28, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 33, in <module>
    from . import compat
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 38, in <module>
    from . import v2
  File "/usr/local/lib/python3.9/dist-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 332, in <module>
    from tensorboard.summary._tf import summary
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 19, in <module>
    from . import pywrap_tensorflow
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 22, in <module>
    from .io import gfile
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/tensorflow_stub/io/__init__.py", line 17, in <module>
    from . import gfile  # noqa
  File "/usr/local/lib/python3.9/dist-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 40, in <module>
    import fsspec
  File "/usr/local/lib/python3.9/dist-packages/fsspec/__init__.py", line 3, in <module>
    from . import _version, caching
  File "/usr/local/lib/python3.9/dist-packages/fsspec/caching.py", line 9, in <module>
    from concurrent.futures import ThreadPoolExecutor
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/usr/lib/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__
    from .thread import ThreadPoolExecutor as te
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "/usr/lib/python3.9/threading.py", line 1414, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown
```

**Comment by l15y** [comment]
1.进行知识库索引
2.配置模型文件位置
