### ISSUE TITLE
求帮助

### ISSUE THREAD

**Issue by adrianlgq** [l15y/wenda#42]
Traceback (most recent call last):
  File "C:\Users\adria\AI\chatglm-6b\wenda-main\GLM6BAPI.py", line 149, in <module>
    import zhishiku
  File "C:\Users\adria\AI\chatglm-6b\wenda-main\zhishiku.py", line 5, in <module>
    ix = storage.open_index()
  File "C:\Users\adria\anaconda3\envs\wendaGLM\lib\site-packages\whoosh\filedb\filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "C:\Users\adria\anaconda3\envs\wendaGLM\lib\site-packages\whoosh\index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "C:\Users\adria\anaconda3\envs\wendaGLM\lib\site-packages\whoosh\index.py", line 618, in read
    raise EmptyIndexError("Index %r does not exist in %r"
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('sy')

不知道是不是环境出问题了？配置好好几次 都是一样的错误

**Comment by l15y** [comment]
先运行gendata构建索引
