### ISSUE TITLE
run_data_processing 时提示找不到库simcse-chinese-roberta-wwm-ext.

### ISSUE THREAD

**Issue by wangfh5** [l15y/wenda#50]
glm模型地址 model/chatglm-6b rwkv模型地址 model/RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth rwkv模型参数 cuda fp16 日志记录 True 知识库类型 x embeddings模型地址 model/simcse-chinese-roberta-wwm-ext vectorstore保存地址 xw LLM模型类型 glm6b chunk_size 400 chunk_count 3 开始读取数据 Traceback (most recent call last):   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status     response.raise_for_status()   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status     raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/model/simcse-chinese-roberta-wwm-ext  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/home/wangfh5/AIGC_projects/wenda/plugins/gen_data_x.py", line 39, in <module>     embeddings = HuggingFaceEmbeddings(model_name=settings.embeddings_path)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 39, in __init__     self.client = sentence_transformers.SentenceTransformer(self.model_name)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 87, in __init__     snapshot_download(model_name_or_path,   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/sentence_transformers/util.py", line 442, in snapshot_download     model_info = _api.model_info(repo_id=repo_id, revision=revision, token=token)                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn     return fn(*args, **kwargs)            ^^^^^^^^^^^^^^^^^^^   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 1624, in model_info     hf_raise_for_status(r)   File "/home/wangfh5/anaconda3/envs/wenda/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 291, in hf_raise_for_status     raise RepositoryNotFoundError(message, response) from e huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6432b193-63f16cd13cfc24fd7ce973a3)  Repository Not Found for url: https://huggingface.co/api/models/model/simcse-chinese-roberta-wwm-ext.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

**Comment by wangfh5** [comment]
我自己下载放进model文件夹了
