### ISSUE TITLE
用git，懒人包调用rwkv都报这个错误

### ISSUE THREAD

**Issue by LifeNT** [l15y/wenda#51]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\LLM\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\LLM\wenda\WPy64-38100\python-3.8.10.amd64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "rwkvAPI.py", line 142, in load_model
    from rwkv.model import RWKV # pip install rwkv
ModuleNotFoundError: No module named 'rwkv'

**Comment by l15y** [comment]
pip install rwkv
