### ISSUE TITLE
刚刚更新了一下，网页打不开了

### ISSUE THREAD

**Issue by LifeNT** [l15y/wenda#59]
Error: 500 Internal Server Error
Sorry, the requested URL 'http://127.0.0.1:17860/' caused an error:

Internal Server Error
Exception:
AttributeError("'LocalResponse' object has no attribute 'setHeader'")
Traceback:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\bottle.py", line 876, in _handle
    return route.call(**args)
  File "C:\python\lib\site-packages\bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "E:\wenda\wenda.py", line 19, in index
    response.setHeader( "Pragma", "no-cache" );
AttributeError: 'LocalResponse' object has no attribute 'setHeader'

**Comment by diannaojiang** [comment]
在修（

**Comment by LifeNT** [comment]
大佬辛苦
