### ISSUE TITLE
txt文件夹有没有可能支持树状目录的读取

### ISSUE THREAD

**Issue by wangfh5** [l15y/wenda#69]
目前只能把所有的本地知识文件都放在txt文件夹里面, 如果往文件夹中再塞一个文件夹, 数据处理就会报错
```
Traceback (most recent call last):
  File "/home/wangfh5/AIGC_projects/wenda/plugins/gen_data_x.py", line 21, in <module>
    with open(floder+'/'+file,"r",encoding='utf-16') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'txt/Chapter 19'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangfh5/AIGC_projects/wenda/plugins/gen_data_x.py", line 24, in <module>
    with open(floder+'/'+file,"r",encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'txt/Chapter 19'
```
能不能增加对文件夹读取的支持?

**Comment by TheReluctantHeroes** [comment]
你参考 https://github.com/l15y/wenda/pull/75 修改gen_data_x.py即可，实测可以
